<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $this->escape($this->pageTitle); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/style.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-theme.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.min.css" type="text/css">
    
    <!-- Scripts -->
    <!--[if lt IE 9]><script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/html5shiv.js"></script><![endif]-->
    <!--[if lt IE 9]><script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/respond.min.js"></script><![endif]-->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class=""><a href="<?php echo $this->baseUrl('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    <li class=""><a href="<?php echo $this->baseUrl('album') ?>"><?php echo $this->translate('Album') ?></a></li>
                </ul>
                
                <?php echo $this->loginForm->setAction($this->url()); ?>
                
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="sidebar col-md-2">
                <?php echo $this->layout()->sidebar; ?>
            </div>
        
            <div class="main col-md-10">
                <?php echo $this->layout()->content; ?>
            </div>
            
        </div>
    </div>
</body>
</html>
